name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-debian-system:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: apt-get -y update && apt-get install -y libgmp-dev build-essential cmake

    - name: Cmake
      run: cmake -G "Unix Makefiles" -B./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build ./build

  build-debian-conan:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: apt-get -y update && apt-get install -y python3 python3-pip build-essential cmake

    - name: Install conan
      run: pip install conan --break-system-packages

    - name: Init conan
      run: conan profile detect

    - name: Install deps with conan
      run: conan install . -of ./build -s build_type=Release --build=missing

    - name: Cmake
      working-directory: ./build
      run: bash conanbuild.sh && cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_SYSTEM_LIBS=0

    - name: Build
      working-directory: ./build
      run: cmake --build .

  build-fedora-system:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dnf -y install gmp-devel make automake clang cmake

    - name: Cmake
      run: cmake -G "Unix Makefiles" -B./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build ./build
