name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-system:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: apt-get install -y libgmp-dev

    - name: Cmake
      run: cmake -G "Unix Makefiles" -B${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: make
      working-directory: ${{runner.workspace}}/build
      run: make