name: Release

on:
  push:
    branches:
      - main
      - feature/refresh
    tags:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  deb:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: apt-get -y update && apt-get install -y libgmp-dev build-essential cmake

    - name: Cmake
      run: cmake -G "Unix Makefiles" -B./build1 -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build ./build

    - name: Package
      id: package
      working-directory: build
      run: |
        cpack -G "DEB" -P libbncsutil-${{ github.ref }}.deb

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libbncsutil-${{ github.ref }}.deb
        tag_name: ${{ github.ref }}
        title: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: dnf -y install gmp-devel make automake clang cmake

    - name: Cmake
      run: cmake -G "Unix Makefiles" -B./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build ./build

    - name: Package
      working-directory: build
      run: cpack -G "RPM"
